version: '3.3'

services:
  prometheus-bot:
    container_name: telegrambot
    image: prometheus-bot:0.0.1

    volumes:
      - /etc/telegrambot/:/etc/telegrambot/
    ports:
      - 9087:9087
    restart: always
